name: todo_list_provider
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.2
  synchronized: ^3.1.0+1
  path: ^1.9.0
  sqflite_common: ^2.5.4
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
